name = "vault"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "api.vaultdotenv.io/*", zone_name = "vaultdotenv.io" },
  { pattern = "vault.satinvoice.com/*", zone_name = "satinvoice.com" }
]

[vars]
STRIPE_PRICE_PRO = "price_1TF1xXEh5MxndipbfkiJuZYa"
STRIPE_PRICE_TEAM = "price_1TF1xbEh5MxndipbqpWgW4qJ"

[[d1_databases]]
binding = "DB"
database_name = "vault-db"
database_id = "b552f757-7630-44c7-a7c9-547d53bb7009"
